#Deploy OVA
- hosts: vCenter
  connection: local
  gather_facts: true
  roles:
    - roles/General-Roles/date_time
    - roles/vSphere-Roles/vSphere/create_resource_pool
    - roles/vSphere-Roles/BIG_IP/deploy_f5_ova
    - roles/vSphere-Roles/BIG_IP/prep_f5_linked_clone
    - roles/vSphere-Roles/BIG_IP/clone_f5_vm
    - roles/vSphere-Roles/vSphere/vmware_tools_wait
    - roles/vSphere-Roles/BIG_IP/create_dyn_group_f5_vms